In [1]:
import pandas as pd
import numpy as np

In [2]:
#Files to load
file_to_load = "Resources/MC_Master_Final.csv"
#Read the CSV into a DataFrame
housing_df = pd.read_csv(file_to_load)
housing_df.head()

/Users/nicolehousekeeper/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (0,16,19,39,40,41,43,46,47,48,77,83,91) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,MLSNumber,Address,Category,Status,SoldPrice,OriginalPrice,CurrentPrice,Last List Price,Type,DOM,...,Parking,ExteriorFeatures,ExteriorMaterial,Main Roof,Foundation,PorchDeck,SwimmingPoolType,OtherStructures,OriginatingMLS,Structure Type
0,1002390593,1019 Maple Ave,RES,Closed,"$329,000","$329,000","$329,000",NaN,NaN,12,...,NaN,NaN,VinylSiding,NaN,NaN,NaN,NaN,NaN,MRIS,Detached
1,1002388281,9701 Fields Rd #1806,RES,Closed,"$127,000","$129,900","$129,900",NaN,NaN,33,...,NaN,NaN,Brick,NaN,NaN,NaN,NaN,NaN,MRIS,Unit/Flat/Apartment
2,1002388133,2211 Washington Ave #W-102,RES,Closed,"$202,000","$207,000","$207,000",NaN,NaN,29,...,NaN,NaN,Brick,NaN,NaN,NaN,NaN,NaN,MRIS,Unit/Flat/Apartment
3,1002385453,3701 Kayson St,RES,Closed,"$339,000","$375,000","$349,900","$375,000",NaN,31,...,PavedDriveway,SecureStorage,"Brick,Combination",Composite,NaN,Patios,NaN,NaN,MRIS,Detached
4,1002384775,3117 University Blvd W #B4,RES,Closed,"$139,900","$139,900","$139,900",NaN,NaN,24,...,"Assigned,RentedPermitRequired",NaN,Brick,NaN,NaN,NaN,NaN,NaN,MRIS,Unit/Flat/Apartment

In [3]:
list(housing_df.columns.values)

['MLSNumber',
 'Address',
 'Category',
 'Status',
 'SoldPrice',
 'OriginalPrice',
 'CurrentPrice',
 'Last List Price',
 'Type',
 'DOM',
 'PMP',
 'ListDate',
 'StatusDate',
 'Agreement of Sale/Signed Lease Date',
 'SettledDate',
 'LastModifiedDate',
 'StreetNumber',
 'StreetName',
 'UnitNumber',
 'CrossStreet',
 'FloorNumber',
 '#ofStories',
 'City',
 'State',
 'Zip Code',
 'County',
 'MLSArea',
 'Township',
 'Subdivision',
 'School District',
 'Schools-Elementary',
 'Schools-Middle',
 'Schools-HighSchool',
 'Assessment',
 'TaxAnnualTotal',
 'TaxYear',
 'New Construction YN',
 'HomeBuilt',
 'EarliestPossession',
 'AdditionalBankOwned',
 'AdditionalThirdPartyApproval',
 'AdditionalShortSale',
 'Concessions YN',
 'Concessions Remarks',
 'SellerConcessionsAmount',
 'FinalFinancing',
 'FinalShortSale',
 'FinalThirdPartyApproval',
 'FinalBankOwned',
 'Acres',
 'LotSqFt',
 'LotDimensions',
 'LotDescription',
 'ShoreWater',
 'Ownership',
 'Senior Community YN',
 'Condo/Coop Assoc YN',
 'HOA YN',
 'AssociationFee',
 'AssociationFeeFrequency',
 'FeeIncludes',
 'ExtraFee(s)',
 'Age',
 'InteriorSqFt',
 'Interior SqFt Source',
 'AboveGradeSqFt',
 'BelowGradeSqFt',
 'PropertyCondition',
 'Bedrooms',
 'Baths',
 'BathsFull',
 'PartialBaths',
 'Design',
 'Style',
 'NumberofStories',
 'RoomCount',
 'InteriorFeatures',
 'Flooring',
 'Central Air YN',
 'Cooling',
 'PrimaryHeat',
 'HeatDelivery',
 'HotWater',
 'ElectricalSystem',
 'Water',
 'Sewer',
 'Fireplace YN',
 'FireplaceCount',
 'FireplaceFeatures',
 'KitchenAppliancesFeatures',
 'CookingFuel',
 'Other Rooms',
 'LaundryHookUps',
 'Basement YN',
 'BasementType',
 'BasementDescription',
 'BasementFootprintPct',
 'BasementFinishedPct',
 'Garage YN',
 'GarageSpaces',
 'GarageFeatures',
 'Parking',
 'ExteriorFeatures',
 'ExteriorMaterial',
 'Main Roof',
 'Foundation',
 'PorchDeck',
 'SwimmingPoolType',
 'OtherStructures',
 'OriginatingMLS ',
 'Structure Type ']

In [4]:
# Drop extra columns
clean_housing_df = housing_df[['MLSNumber', 'Address', 'SoldPrice', 'CurrentPrice', 'ListDate', 'SettledDate', '#ofStories', 'City', 'Zip Code', 'Subdivision', 'New Construction YN', 'Age', 'InteriorSqFt', 'Bedrooms', 'Baths', 'Garage YN', 'Structure Type ']]
clean_housing_df.head()

,MLSNumber,Address,SoldPrice,CurrentPrice,ListDate,SettledDate,#ofStories,City,Zip Code,Subdivision,New Construction YN,Age,InteriorSqFt,Bedrooms,Baths,Garage YN,Structure Type
0,1002390593,1019 Maple Ave,"$329,000","$329,000",11/21/2015,1/4/2016,"Lower1,Main",Rockville,20851,SILVER ROCK,No,1953,NaN,3.0,2.0,No,Detached
1,1002388281,9701 Fields Rd #1806,"$127,000","$129,900",11/9/2015,1/4/2016,Main,Gaithersburg,20878,WASHINGTON TOWER CODM,No,1966,446.0,0.0,1.0,No,Unit/Flat/Apartment
2,1002388133,2211 Washington Ave #W-102,"$202,000","$207,000",11/9/2015,1/4/2016,Main,Silver Spring,20910,ROCK CREEK APTS CODM 2,No,1948,671.0,1.0,1.0,No,Unit/Flat/Apartment
3,1002385453,3701 Kayson St,"$339,000","$349,900",10/24/2015,1/4/2016,"Lower1,Main,Upper1",Silver Spring,20906,CONN AVE ESTATES,No,1955,NaN,4.0,2.0,No,Detached
4,1002384775,3117 University Blvd W #B4,"$139,900","$139,900",10/28/2015,1/4/2016,Main,Kensington,20895,MONTGOMERY CENTURY,No,1973,754.0,1.0,1.0,No,Unit/Flat/Apartment

In [5]:
# Set index column
clean_housing_df = clean_housing_df.set_index('MLSNumber')
clean_housing_df.head()

,Address,SoldPrice,CurrentPrice,ListDate,SettledDate,#ofStories,City,Zip Code,Subdivision,New Construction YN,Age,InteriorSqFt,Bedrooms,Baths,Garage YN,Structure Type
MLSNumber,,,,,,,,,,,,,,,,
1002390593,1019 Maple Ave,"$329,000","$329,000",11/21/2015,1/4/2016,"Lower1,Main",Rockville,20851,SILVER ROCK,No,1953,NaN,3.0,2.0,No,Detached
1002388281,9701 Fields Rd #1806,"$127,000","$129,900",11/9/2015,1/4/2016,Main,Gaithersburg,20878,WASHINGTON TOWER CODM,No,1966,446.0,0.0,1.0,No,Unit/Flat/Apartment
1002388133,2211 Washington Ave #W-102,"$202,000","$207,000",11/9/2015,1/4/2016,Main,Silver Spring,20910,ROCK CREEK APTS CODM 2,No,1948,671.0,1.0,1.0,No,Unit/Flat/Apartment
1002385453,3701 Kayson St,"$339,000","$349,900",10/24/2015,1/4/2016,"Lower1,Main,Upper1",Silver Spring,20906,CONN AVE ESTATES,No,1955,NaN,4.0,2.0,No,Detached
1002384775,3117 University Blvd W #B4,"$139,900","$139,900",10/28/2015,1/4/2016,Main,Kensington,20895,MONTGOMERY CENTURY,No,1973,754.0,1.0,1.0,No,Unit/Flat/Apartment

In [6]:
# Find null rows
clean_housing_df.isnull().sum()

Address                    0
SoldPrice                  1
CurrentPrice               0
ListDate                   0
SettledDate                0
#ofStories                 1
City                       0
Zip Code                   0
Subdivision                0
New Construction YN        0
Age                        0
InteriorSqFt           13555
Bedrooms                   3
Baths                      9
Garage YN                  0
Structure Type           133
dtype: int64

In [7]:
# Drop null rows
clean_housing_df = clean_housing_df.dropna()
clean_housing_df

,Address,SoldPrice,CurrentPrice,ListDate,SettledDate,#ofStories,City,Zip Code,Subdivision,New Construction YN,Age,InteriorSqFt,Bedrooms,Baths,Garage YN,Structure Type
MLSNumber,,,,,,,,,,,,,,,,
1002388281,9701 Fields Rd #1806,"$127,000","$129,900",11/9/2015,1/4/2016,Main,Gaithersburg,20878,WASHINGTON TOWER CODM,No,1966,446.0,0.0,1.0,No,Unit/Flat/Apartment
1002388133,2211 Washington Ave #W-102,"$202,000","$207,000",11/9/2015,1/4/2016,Main,Silver Spring,20910,ROCK CREEK APTS CODM 2,No,1948,671.0,1.0,1.0,No,Unit/Flat/Apartment
1002384775,3117 University Blvd W #B4,"$139,900","$139,900",10/28/2015,1/4/2016,Main,Kensington,20895,MONTGOMERY CENTURY,No,1973,754.0,1.0,1.0,No,Unit/Flat/Apartment
1002382327,10201 Grosvenor Pl #210,"$195,000","$199,900",10/15/2015,1/4/2016,Main,Rockville,20852,GROSVENOR PARK,No,1972,851.0,1.0,1.0,No,Unit/Flat/Apartment
1002382267,10301 Rossmore Ct,"$840,000","$850,000",10/22/2015,1/4/2016,"Lower1,Lower2,Main,Upper1",Bethesda,20814,WILDWOOD KNOLLS,No,1963,3060.0,4.0,4.0,Yes,Detached
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MDMC2005770,1 Paca Pl,"$625,000","$625,000",7/22/2021,9/16/2021,"Main,Upper1",Rockville,20852,HUNGERFORD,No,1955,2237.0,4.0,3.0,Yes,Detached
MDMC753990,1108 Clagett Dr,"$499,500","$509,000",7/15/2021,9/16/2021,Main,Rockville,20851,ROCKCREST,No,1951,1457.0,3.0,3.0,Yes,Detached
MDMC2003756,11307 Galt Ave,"$410,000","$445,000",7/26/2021,9/16/2021,"Lower1,Main,Upper1",Silver Spring,20902,WHEATON HILLS,No,1950,1872.0,4.0,2.0,No,Detached
MDMC763464,8809 Thomas Lea Ter,"$400,000","$374,900",6/24/2021,9/16/2021,"Lower1,Main,Upper1",Montgomery Village,20886,THE REACH,No,1986,2160.0,4.0,4.0,No,Interior Row/Townhouse
MDMC762586,16 Wimbledon Ct,"$379,900","$379,000",6/12/2021,9/16/2021,"Lower1,Main,Upper1",Silver Spring,20906,LONGMEAD,No,1987,1280.0,4.0,4.0,No,Interior Row/Townhouse

In [9]:
list(clean_housing_df.columns.values)

['Address',
 'SoldPrice',
 'CurrentPrice',
 'ListDate',
 'SettledDate',
 '#ofStories',
 'City',
 'Zip Code',
 'Subdivision',
 'New Construction YN',
 'Age',
 'InteriorSqFt',
 'Bedrooms',
 'Baths',
 'Garage YN',
 'Structure Type ']

In [12]:
clean_housing_df.to_csv('Resources/Clean_MC_Master.csv', index=True)